/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EndorsingPowerEndorsementOperation {
    #[serde(rename = "branch")]
    pub branch: crate::models::BlockHash,
    #[serde(rename = "contents")]
    pub contents: Vec<crate::models::Model007PsDelph1OperationAlphaContents>,
    #[serde(rename = "signature")]
    pub signature: crate::models::Signature,
}

impl EndorsingPowerEndorsementOperation {
    pub fn new(branch: crate::models::BlockHash, contents: Vec<crate::models::Model007PsDelph1OperationAlphaContents>, signature: crate::models::Signature) -> EndorsingPowerEndorsementOperation {
        EndorsingPowerEndorsementOperation {
            branch,
            contents,
            signature,
        }
    }
}


