/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HelpersPreapplyBlockProtocolData {
    #[serde(rename = "protocol")]
    pub protocol: Protocol,
    #[serde(rename = "priority")]
    pub priority: i32,
    #[serde(rename = "proof_of_work_nonce")]
    pub proof_of_work_nonce: String,
    #[serde(rename = "seed_nonce_hash", skip_serializing_if = "Option::is_none")]
    pub seed_nonce_hash: Option<crate::models::CycleNonce>,
    #[serde(rename = "signature")]
    pub signature: crate::models::Signature,
}

impl HelpersPreapplyBlockProtocolData {
    pub fn new(protocol: Protocol, priority: i32, proof_of_work_nonce: String, signature: crate::models::Signature) -> HelpersPreapplyBlockProtocolData {
        HelpersPreapplyBlockProtocolData {
            protocol,
            priority,
            proof_of_work_nonce,
            seed_nonce_hash: None,
            signature,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Protocol {
    #[serde(rename = "PsDELPH1Kxsxt8f9eWbxQeRxkjfbxoqM52jvs5Y5fBxWWh4ifpo")]
    PsDELPH1Kxsxt8f9eWbxQeRxkjfbxoqM52jvs5Y5fBxWWh4ifpo,
}

