/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivateAccount1 {
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "pkh")]
    pub pkh: crate::models::Ed25519PublicKeyHash,
    #[serde(rename = "secret")]
    pub secret: String,
    #[serde(rename = "metadata")]
    pub metadata: crate::models::SeedNonceRevelation1Metadata,
}

impl ActivateAccount1 {
    pub fn new(kind: Kind, pkh: crate::models::Ed25519PublicKeyHash, secret: String, metadata: crate::models::SeedNonceRevelation1Metadata) -> ActivateAccount1 {
        ActivateAccount1 {
            kind,
            pkh,
            secret,
            metadata,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "activate_account")]
    ActivateAccount,
}

