/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Backtracked {
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<serde_json::Value>>,
    /// Decimal representation of a positive big number
    #[serde(rename = "consumed_gas", skip_serializing_if = "Option::is_none")]
    pub consumed_gas: Option<String>,
    /// Decimal representation of a positive big number
    #[serde(rename = "consumed_milligas", skip_serializing_if = "Option::is_none")]
    pub consumed_milligas: Option<String>,
}

impl Backtracked {
    pub fn new(status: Status) -> Backtracked {
        Backtracked {
            status,
            errors: None,
            consumed_gas: None,
            consumed_milligas: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "backtracked")]
    Backtracked,
}

