/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Ballot1 {
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "source")]
    pub source: crate::models::SignaturePublicKeyHash,
    #[serde(rename = "period")]
    pub period: i32,
    #[serde(rename = "proposal")]
    pub proposal: crate::models::ProtocolHash,
    #[serde(rename = "ballot")]
    pub ballot: Ballot,
    #[serde(rename = "metadata")]
    pub metadata: serde_json::Value,
}

impl Ballot1 {
    pub fn new(kind: Kind, source: crate::models::SignaturePublicKeyHash, period: i32, proposal: crate::models::ProtocolHash, ballot: Ballot, metadata: serde_json::Value) -> Ballot1 {
        Ballot1 {
            kind,
            source,
            period,
            proposal,
            ballot,
            metadata,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "ballot")]
    Ballot,
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Ballot {
    #[serde(rename = "nay")]
    Nay,
    #[serde(rename = "yay")]
    Yay,
    #[serde(rename = "pass")]
    Pass,
}

