/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockHeaderMetadataMaxOperationListLength {
    #[serde(rename = "max_size")]
    pub max_size: i32,
    #[serde(rename = "max_op", skip_serializing_if = "Option::is_none")]
    pub max_op: Option<i32>,
}

impl BlockHeaderMetadataMaxOperationListLength {
    pub fn new(max_size: i32) -> BlockHeaderMetadataMaxOperationListLength {
        BlockHeaderMetadataMaxOperationListLength {
            max_size,
            max_op: None,
        }
    }
}


