/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockHeaderMetadata {
    #[serde(rename = "protocol")]
    pub protocol: Protocol,
    #[serde(rename = "next_protocol")]
    pub next_protocol: NextProtocol,
    #[serde(rename = "test_chain_status")]
    pub test_chain_status: crate::models::TestChainStatus,
    #[serde(rename = "max_operations_ttl")]
    pub max_operations_ttl: i32,
    #[serde(rename = "max_operation_data_length")]
    pub max_operation_data_length: i32,
    #[serde(rename = "max_block_header_length")]
    pub max_block_header_length: i32,
    #[serde(rename = "max_operation_list_length")]
    pub max_operation_list_length: Vec<crate::models::BlockHeaderMetadataMaxOperationListLength>,
}

impl BlockHeaderMetadata {
    pub fn new(protocol: Protocol, next_protocol: NextProtocol, test_chain_status: crate::models::TestChainStatus, max_operations_ttl: i32, max_operation_data_length: i32, max_block_header_length: i32, max_operation_list_length: Vec<crate::models::BlockHeaderMetadataMaxOperationListLength>) -> BlockHeaderMetadata {
        BlockHeaderMetadata {
            protocol,
            next_protocol,
            test_chain_status,
            max_operations_ttl,
            max_operation_data_length,
            max_block_header_length,
            max_operation_list_length,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Protocol {
    #[serde(rename = "ProtoGenesisGenesisGenesisGenesisGenesisGenesk612im")]
    ProtoGenesisGenesisGenesisGenesisGenesisGenesk612im,
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NextProtocol {
    #[serde(rename = "PsDELPH1Kxsxt8f9eWbxQeRxkjfbxoqM52jvs5Y5fBxWWh4ifpo")]
    PsDELPH1Kxsxt8f9eWbxQeRxkjfbxoqM52jvs5Y5fBxWWh4ifpo,
}

