/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Delegation {
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "source")]
    pub source: crate::models::Model007PsDelph1ContractId,
    #[serde(rename = "nonce")]
    pub nonce: i32,
    #[serde(rename = "delegate", skip_serializing_if = "Option::is_none")]
    pub delegate: Option<crate::models::SignaturePublicKeyHash>,
    #[serde(rename = "result")]
    pub result: crate::models::Model007PsDelph1OperationAlphaOperationResultDelegation,
}

impl Delegation {
    pub fn new(kind: Kind, source: crate::models::Model007PsDelph1ContractId, nonce: i32, result: crate::models::Model007PsDelph1OperationAlphaOperationResultDelegation) -> Delegation {
        Delegation {
            kind,
            source,
            nonce,
            delegate: None,
            result,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "delegation")]
    Delegation,
}

