/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Delegation1 {
    #[serde(rename = "source")]
    pub source: crate::models::Model007PsDelph1ContractId,
    #[serde(rename = "nonce")]
    pub nonce: i32,
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "delegate", skip_serializing_if = "Option::is_none")]
    pub delegate: Option<crate::models::SignaturePublicKeyHash>,
}

impl Delegation1 {
    pub fn new(source: crate::models::Model007PsDelph1ContractId, nonce: i32, kind: Kind) -> Delegation1 {
        Delegation1 {
            source,
            nonce,
            kind,
            delegate: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "delegation")]
    Delegation,
}

