/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DoubleBakingEvidence1 {
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "bh1")]
    pub bh1: crate::models::Model007PsDelph1BlockHeaderAlphaFullHeader,
    #[serde(rename = "bh2")]
    pub bh2: crate::models::Model007PsDelph1BlockHeaderAlphaFullHeader,
    #[serde(rename = "metadata")]
    pub metadata: crate::models::SeedNonceRevelation1Metadata,
}

impl DoubleBakingEvidence1 {
    pub fn new(kind: Kind, bh1: crate::models::Model007PsDelph1BlockHeaderAlphaFullHeader, bh2: crate::models::Model007PsDelph1BlockHeaderAlphaFullHeader, metadata: crate::models::SeedNonceRevelation1Metadata) -> DoubleBakingEvidence1 {
        DoubleBakingEvidence1 {
            kind,
            bh1,
            bh2,
            metadata,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "double_baking_evidence")]
    DoubleBakingEvidence,
}

