/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DoubleEndorsementEvidence {
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "op1")]
    pub op1: crate::models::Model007PsDelph1InlinedEndorsement,
    #[serde(rename = "op2")]
    pub op2: crate::models::Model007PsDelph1InlinedEndorsement,
}

impl DoubleEndorsementEvidence {
    pub fn new(kind: Kind, op1: crate::models::Model007PsDelph1InlinedEndorsement, op2: crate::models::Model007PsDelph1InlinedEndorsement) -> DoubleEndorsementEvidence {
        DoubleEndorsementEvidence {
            kind,
            op1,
            op2,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "double_endorsement_evidence")]
    DoubleEndorsementEvidence,
}

