/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Ed25519PublicKeyHash {
    #[serde(rename = "invalid_utf8_string")]
    pub invalid_utf8_string: Vec<i32>,
}

impl Ed25519PublicKeyHash {
    pub fn new(invalid_utf8_string: Vec<i32>) -> Ed25519PublicKeyHash {
        Ed25519PublicKeyHash {
            invalid_utf8_string,
        }
    }
}


