/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Endorsement1Metadata {
    #[serde(rename = "balance_updates")]
    pub balance_updates: Vec<crate::models::OneOfobjectobjectobjectobject>,
    #[serde(rename = "delegate")]
    pub delegate: crate::models::SignaturePublicKeyHash,
    #[serde(rename = "slots")]
    pub slots: Vec<i32>,
}

impl Endorsement1Metadata {
    pub fn new(balance_updates: Vec<crate::models::OneOfobjectobjectobjectobject>, delegate: crate::models::SignaturePublicKeyHash, slots: Vec<i32>) -> Endorsement1Metadata {
        Endorsement1Metadata {
            balance_updates,
            delegate,
            slots,
        }
    }
}


