/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Endorsement1 {
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "level")]
    pub level: i32,
    #[serde(rename = "metadata")]
    pub metadata: crate::models::Endorsement1Metadata,
}

impl Endorsement1 {
    pub fn new(kind: Kind, level: i32, metadata: crate::models::Endorsement1Metadata) -> Endorsement1 {
        Endorsement1 {
            kind,
            level,
            metadata,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "endorsement")]
    Endorsement,
}

