/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Failed {
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "errors")]
    pub errors: Vec<serde_json::Value>,
}

impl Failed {
    pub fn new(status: Status, errors: Vec<serde_json::Value>) -> Failed {
        Failed {
            status,
            errors,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "failed")]
    Failed,
}

