/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Forking {
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "protocol")]
    pub protocol: crate::models::ProtocolHash,
    #[serde(rename = "expiration")]
    pub expiration: crate::models::TimestampProtocol,
}

impl Forking {
    pub fn new(status: Status, protocol: crate::models::ProtocolHash, expiration: crate::models::TimestampProtocol) -> Forking {
        Forking {
            status,
            protocol,
            expiration,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "forking")]
    Forking,
}

