/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenericPrimAnyNumberOfArgsWithOrWithoutAnnot {
    #[serde(rename = "prim")]
    pub prim: crate::models::Model007PsDelph1MichelsonV1Primitives,
    #[serde(rename = "args", skip_serializing_if = "Option::is_none")]
    pub args: Option<Vec<crate::models::Micheline007PsDelph1MichelsonV1Expression>>,
    #[serde(rename = "annots", skip_serializing_if = "Option::is_none")]
    pub annots: Option<Vec<String>>,
}

impl GenericPrimAnyNumberOfArgsWithOrWithoutAnnot {
    pub fn new(prim: crate::models::Model007PsDelph1MichelsonV1Primitives) -> GenericPrimAnyNumberOfArgsWithOrWithoutAnnot {
        GenericPrimAnyNumberOfArgsWithOrWithoutAnnot {
            prim,
            args: None,
            annots: None,
        }
    }
}


