/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2004FrozenBalanceByCycle {
    #[serde(rename = "cycle")]
    pub cycle: i32,
    /// Decimal representation of a positive big number
    #[serde(rename = "deposit")]
    pub deposit: String,
    /// Decimal representation of a positive big number
    #[serde(rename = "fees")]
    pub fees: String,
    /// Decimal representation of a positive big number
    #[serde(rename = "rewards")]
    pub rewards: String,
}

impl InlineResponse2004FrozenBalanceByCycle {
    pub fn new(cycle: i32, deposit: String, fees: String, rewards: String) -> InlineResponse2004FrozenBalanceByCycle {
        InlineResponse2004FrozenBalanceByCycle {
            cycle,
            deposit,
            fees,
            rewards,
        }
    }
}


