/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20010 {
    #[serde(rename = "block")]
    pub block: String,
}

impl InlineResponse20010 {
    pub fn new(block: String) -> InlineResponse20010 {
        InlineResponse20010 {
            block,
        }
    }
}


