/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20019 {
    #[serde(rename = "pkh")]
    pub pkh: crate::models::SignaturePublicKeyHash,
    #[serde(rename = "ballot")]
    pub ballot: Ballot,
}

impl InlineResponse20019 {
    pub fn new(pkh: crate::models::SignaturePublicKeyHash, ballot: Ballot) -> InlineResponse20019 {
        InlineResponse20019 {
            pkh,
            ballot,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Ballot {
    #[serde(rename = "nay")]
    Nay,
    #[serde(rename = "yay")]
    Yay,
    #[serde(rename = "pass")]
    Pass,
}

