/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2002 {
    /// Decimal representation of a positive big number
    #[serde(rename = "balance")]
    pub balance: String,
    #[serde(rename = "delegate", skip_serializing_if = "Option::is_none")]
    pub delegate: Option<crate::models::SignaturePublicKeyHash>,
    #[serde(rename = "script", skip_serializing_if = "Option::is_none")]
    pub script: Option<crate::models::Model007PsDelph1ScriptedContracts>,
    /// Decimal representation of a positive big number
    #[serde(rename = "counter", skip_serializing_if = "Option::is_none")]
    pub counter: Option<String>,
}

impl InlineResponse2002 {
    pub fn new(balance: String) -> InlineResponse2002 {
        InlineResponse2002 {
            balance,
            delegate: None,
            script: None,
            counter: None,
        }
    }
}


