/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2003Unreachable {
    #[serde(rename = "path")]
    pub path: Vec<crate::models::Model007PsDelph1MichelsonV1Primitives>,
}

impl InlineResponse2003Unreachable {
    pub fn new(path: Vec<crate::models::Model007PsDelph1MichelsonV1Primitives>) -> InlineResponse2003Unreachable {
        InlineResponse2003Unreachable {
            path,
        }
    }
}


