/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20021 {
    #[serde(rename = "pkh")]
    pub pkh: crate::models::SignaturePublicKeyHash,
    #[serde(rename = "rolls")]
    pub rolls: i32,
}

impl InlineResponse20021 {
    pub fn new(pkh: crate::models::SignaturePublicKeyHash, rolls: i32) -> InlineResponse20021 {
        InlineResponse20021 {
            pkh,
            rolls,
        }
    }
}


