/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20014 {
    #[serde(rename = "packed")]
    pub packed: String,
    #[serde(rename = "gas")]
    pub gas: crate::models::OneOfobjectstring,
}

impl InlineResponse20014 {
    pub fn new(packed: String, gas: crate::models::OneOfobjectstring) -> InlineResponse20014 {
        InlineResponse20014 {
            packed,
            gas,
        }
    }
}


