/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject6 {
    #[serde(rename = "script")]
    pub script: crate::models::Micheline007PsDelph1MichelsonV1Expression,
}

impl InlineObject6 {
    pub fn new(script: crate::models::Micheline007PsDelph1MichelsonV1Expression) -> InlineObject6 {
        InlineObject6 {
            script,
        }
    }
}


