/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse200 {
    #[serde(rename = "protocol")]
    pub protocol: Protocol,
    #[serde(rename = "chain_id")]
    pub chain_id: crate::models::ChainId,
    #[serde(rename = "hash")]
    pub hash: crate::models::BlockHash,
    #[serde(rename = "header")]
    pub header: crate::models::RawBlockHeader,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::models::BlockHeaderMetadata>,
    #[serde(rename = "operations")]
    pub operations: Vec<Vec<crate::models::Operation>>,
}

impl InlineResponse200 {
    pub fn new(protocol: Protocol, chain_id: crate::models::ChainId, hash: crate::models::BlockHash, header: crate::models::RawBlockHeader, operations: Vec<Vec<crate::models::Operation>>) -> InlineResponse200 {
        InlineResponse200 {
            protocol,
            chain_id,
            hash,
            header,
            metadata: None,
            operations,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Protocol {
    #[serde(rename = "ProtoGenesisGenesisGenesisGenesisGenesisGenesk612im")]
    ProtoGenesisGenesisGenesisGenesisGenesisGenesk612im,
}

