/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2006 {
    #[serde(rename = "level")]
    pub level: i32,
    #[serde(rename = "delegate")]
    pub delegate: crate::models::SignaturePublicKeyHash,
    #[serde(rename = "priority")]
    pub priority: i32,
    #[serde(rename = "estimated_time", skip_serializing_if = "Option::is_none")]
    pub estimated_time: Option<crate::models::TimestampProtocol>,
}

impl InlineResponse2006 {
    pub fn new(level: i32, delegate: crate::models::SignaturePublicKeyHash, priority: i32) -> InlineResponse2006 {
        InlineResponse2006 {
            level,
            delegate,
            priority,
            estimated_time: None,
        }
    }
}


