/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20017TypeMap {
    /// The location of a node in a Micheline expression tree in prefix order, with zero being the root and adding one for every basic node, sequence and primitive application.
    #[serde(rename = "location")]
    pub location: i32,
    #[serde(rename = "stack_before")]
    pub stack_before: Vec<Vec<crate::models::OneOfmicheline007PsDelph1MichelsonV1Expressionarray>>,
    #[serde(rename = "stack_after")]
    pub stack_after: Vec<Vec<crate::models::OneOfmicheline007PsDelph1MichelsonV1Expressionarray>>,
}

impl InlineResponse20017TypeMap {
    pub fn new(location: i32, stack_before: Vec<Vec<crate::models::OneOfmicheline007PsDelph1MichelsonV1Expressionarray>>, stack_after: Vec<Vec<crate::models::OneOfmicheline007PsDelph1MichelsonV1Expressionarray>>) -> InlineResponse20017TypeMap {
        InlineResponse20017TypeMap {
            location,
            stack_before,
            stack_after,
        }
    }
}


