/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject5 {
    #[serde(rename = "script")]
    pub script: crate::models::Micheline007PsDelph1MichelsonV1Expression,
    #[serde(rename = "entrypoint", skip_serializing_if = "Option::is_none")]
    pub entrypoint: Option<crate::models::Unistring>,
}

impl InlineObject5 {
    pub fn new(script: crate::models::Micheline007PsDelph1MichelsonV1Expression) -> InlineObject5 {
        InlineObject5 {
            script,
            entrypoint: None,
        }
    }
}


