/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject12 {
    #[serde(rename = "data")]
    pub data: crate::models::Micheline007PsDelph1MichelsonV1Expression,
    #[serde(rename = "type")]
    pub _type: crate::models::Micheline007PsDelph1MichelsonV1Expression,
    /// Decimal representation of a big number
    #[serde(rename = "gas", skip_serializing_if = "Option::is_none")]
    pub gas: Option<String>,
}

impl InlineObject12 {
    pub fn new(data: crate::models::Micheline007PsDelph1MichelsonV1Expression, _type: crate::models::Micheline007PsDelph1MichelsonV1Expression) -> InlineObject12 {
        InlineObject12 {
            data,
            _type,
            gas: None,
        }
    }
}


