/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2008 {
    #[serde(rename = "level")]
    pub level: i32,
    #[serde(rename = "delegate")]
    pub delegate: crate::models::SignaturePublicKeyHash,
    #[serde(rename = "slots")]
    pub slots: Vec<i32>,
    #[serde(rename = "estimated_time", skip_serializing_if = "Option::is_none")]
    pub estimated_time: Option<crate::models::TimestampProtocol>,
}

impl InlineResponse2008 {
    pub fn new(level: i32, delegate: crate::models::SignaturePublicKeyHash, slots: Vec<i32>) -> InlineResponse2008 {
        InlineResponse2008 {
            level,
            delegate,
            slots,
            estimated_time: None,
        }
    }
}


