/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20017 {
    #[serde(rename = "type_map")]
    pub type_map: Vec<crate::models::InlineResponse20017TypeMap>,
    #[serde(rename = "gas")]
    pub gas: crate::models::OneOfobjectstring,
}

impl InlineResponse20017 {
    pub fn new(type_map: Vec<crate::models::InlineResponse20017TypeMap>, gas: crate::models::OneOfobjectstring) -> InlineResponse20017 {
        InlineResponse20017 {
            type_map,
            gas,
        }
    }
}


