/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject9 {
    #[serde(rename = "operation")]
    pub operation: crate::models::EndorsingPowerEndorsementOperation,
    #[serde(rename = "chain_id")]
    pub chain_id: crate::models::ChainId,
}

impl InlineObject9 {
    pub fn new(operation: crate::models::EndorsingPowerEndorsementOperation, chain_id: crate::models::ChainId) -> InlineObject9 {
        InlineObject9 {
            operation,
            chain_id,
        }
    }
}


