/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20012Applied {
    #[serde(rename = "hash")]
    pub hash: crate::models::OperationHash,
    #[serde(rename = "branch")]
    pub branch: crate::models::BlockHash,
    #[serde(rename = "data")]
    pub data: String,
}

impl InlineResponse20012Applied {
    pub fn new(hash: crate::models::OperationHash, branch: crate::models::BlockHash, data: String) -> InlineResponse20012Applied {
        InlineResponse20012Applied {
            hash,
            branch,
            data,
        }
    }
}


