/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject3 {
    #[serde(rename = "operations")]
    pub operations: Vec<crate::models::Operation>,
    #[serde(rename = "check_signature", skip_serializing_if = "Option::is_none")]
    pub check_signature: Option<bool>,
}

impl InlineObject3 {
    pub fn new(operations: Vec<crate::models::Operation>) -> InlineObject3 {
        InlineObject3 {
            operations,
            check_signature: None,
        }
    }
}


