/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2005 {
    #[serde(rename = "protocol")]
    pub protocol: Protocol,
    #[serde(rename = "content")]
    pub content: crate::models::OneOfobjectobject,
    #[serde(rename = "signature")]
    pub signature: crate::models::Signature,
}

impl InlineResponse2005 {
    pub fn new(protocol: Protocol, content: crate::models::OneOfobjectobject, signature: crate::models::Signature) -> InlineResponse2005 {
        InlineResponse2005 {
            protocol,
            content,
            signature,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Protocol {
    #[serde(rename = "ProtoGenesisGenesisGenesisGenesisGenesisGenesk612im")]
    ProtoGenesisGenesisGenesisGenesisGenesisGenesk612im,
}

