/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20013 {
    #[serde(rename = "entrypoint_type")]
    pub entrypoint_type: crate::models::Micheline007PsDelph1MichelsonV1Expression,
}

impl InlineResponse20013 {
    pub fn new(entrypoint_type: crate::models::Micheline007PsDelph1MichelsonV1Expression) -> InlineResponse20013 {
        InlineResponse20013 {
            entrypoint_type,
        }
    }
}


