/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20012 {
    #[serde(rename = "shell_header")]
    pub shell_header: crate::models::BlockHeaderShell,
    #[serde(rename = "operations")]
    pub operations: Vec<crate::models::InlineResponse20012Operations>,
}

impl InlineResponse20012 {
    pub fn new(shell_header: crate::models::BlockHeaderShell, operations: Vec<crate::models::InlineResponse20012Operations>) -> InlineResponse20012 {
        InlineResponse20012 {
            shell_header,
            operations,
        }
    }
}


