/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2003 {
    #[serde(rename = "unreachable", skip_serializing_if = "Option::is_none")]
    pub unreachable: Option<Vec<crate::models::InlineResponse2003Unreachable>>,
    #[serde(rename = "entrypoints")]
    pub entrypoints: ::std::collections::HashMap<String, crate::models::Micheline007PsDelph1MichelsonV1Expression>,
}

impl InlineResponse2003 {
    pub fn new(entrypoints: ::std::collections::HashMap<String, crate::models::Micheline007PsDelph1MichelsonV1Expression>) -> InlineResponse2003 {
        InlineResponse2003 {
            unreachable: None,
            entrypoints,
        }
    }
}


