/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject {
    #[serde(rename = "key")]
    pub key: crate::models::Micheline007PsDelph1MichelsonV1Expression,
    #[serde(rename = "type")]
    pub _type: crate::models::Micheline007PsDelph1MichelsonV1Expression,
}

impl InlineObject {
    pub fn new(key: crate::models::Micheline007PsDelph1MichelsonV1Expression, _type: crate::models::Micheline007PsDelph1MichelsonV1Expression) -> InlineObject {
        InlineObject {
            key,
            _type,
        }
    }
}


