/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject2 {
    #[serde(rename = "priority")]
    pub priority: i32,
    #[serde(rename = "nonce_hash", skip_serializing_if = "Option::is_none")]
    pub nonce_hash: Option<crate::models::CycleNonce>,
    #[serde(rename = "proof_of_work_nonce", skip_serializing_if = "Option::is_none")]
    pub proof_of_work_nonce: Option<String>,
}

impl InlineObject2 {
    pub fn new(priority: i32) -> InlineObject2 {
        InlineObject2 {
            priority,
            nonce_hash: None,
            proof_of_work_nonce: None,
        }
    }
}


