/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2009 {
    #[serde(rename = "protocol_data")]
    pub protocol_data: String,
}

impl InlineResponse2009 {
    pub fn new(protocol_data: String) -> InlineResponse2009 {
        InlineResponse2009 {
            protocol_data,
        }
    }
}


