/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20020 {
    #[serde(rename = "yay")]
    pub yay: i32,
    #[serde(rename = "nay")]
    pub nay: i32,
    #[serde(rename = "pass")]
    pub pass: i32,
}

impl InlineResponse20020 {
    pub fn new(yay: i32, nay: i32, pass: i32) -> InlineResponse20020 {
        InlineResponse20020 {
            yay,
            nay,
            pass,
        }
    }
}


