/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject1 {
    #[serde(rename = "endorsement_operation")]
    pub endorsement_operation: crate::models::EndorsingPowerEndorsementOperation,
    #[serde(rename = "chain_id")]
    pub chain_id: crate::models::ChainId,
}

impl InlineObject1 {
    pub fn new(endorsement_operation: crate::models::EndorsingPowerEndorsementOperation, chain_id: crate::models::ChainId) -> InlineObject1 {
        InlineObject1 {
            endorsement_operation,
            chain_id,
        }
    }
}


