/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject11 {
    #[serde(rename = "program")]
    pub program: crate::models::Micheline007PsDelph1MichelsonV1Expression,
    /// Decimal representation of a big number
    #[serde(rename = "gas", skip_serializing_if = "Option::is_none")]
    pub gas: Option<String>,
}

impl InlineObject11 {
    pub fn new(program: crate::models::Micheline007PsDelph1MichelsonV1Expression) -> InlineObject11 {
        InlineObject11 {
            program,
            gas: None,
        }
    }
}


