/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model007PsDelph1OperationAlphaOperationWithMetadata {
    #[serde(rename = "contents")]
    pub contents: Vec<crate::models::Model007PsDelph1OperationAlphaContents>,
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature: Option<crate::models::Signature>,
}

impl Model007PsDelph1OperationAlphaOperationWithMetadata {
    pub fn new(contents: Vec<crate::models::Model007PsDelph1OperationAlphaContents>) -> Model007PsDelph1OperationAlphaOperationWithMetadata {
        Model007PsDelph1OperationAlphaOperationWithMetadata {
            contents,
            signature: None,
        }
    }
}


