/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Model007PsDelph1Entrypoint : Named entrypoint to a Michelson smart contract



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model007PsDelph1Entrypoint {
}

impl Model007PsDelph1Entrypoint {
    /// Named entrypoint to a Michelson smart contract
    pub fn new() -> Model007PsDelph1Entrypoint {
        Model007PsDelph1Entrypoint {
        }
    }
}


