/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model007PsDelph1BlockHeaderAlphaFullHeader {
    #[serde(rename = "level")]
    pub level: i32,
    #[serde(rename = "proto")]
    pub proto: i32,
    #[serde(rename = "predecessor")]
    pub predecessor: crate::models::BlockHash,
    #[serde(rename = "timestamp")]
    pub timestamp: crate::models::TimestampProtocol,
    #[serde(rename = "validation_pass")]
    pub validation_pass: i32,
    #[serde(rename = "operations_hash")]
    pub operations_hash: crate::models::OperationListListHash,
    /// The fitness, or score, of a block, that allow the Tezos to decide which chain is the best. A fitness value is a list of byte sequences. They are compared as follows: shortest lists are smaller; lists of the same length are compared according to the lexicographical order.
    #[serde(rename = "fitness")]
    pub fitness: Vec<String>,
    #[serde(rename = "context")]
    pub context: crate::models::ContextHash,
    #[serde(rename = "priority")]
    pub priority: i32,
    #[serde(rename = "proof_of_work_nonce")]
    pub proof_of_work_nonce: String,
    #[serde(rename = "seed_nonce_hash", skip_serializing_if = "Option::is_none")]
    pub seed_nonce_hash: Option<crate::models::CycleNonce>,
    #[serde(rename = "signature")]
    pub signature: crate::models::Signature,
}

impl Model007PsDelph1BlockHeaderAlphaFullHeader {
    pub fn new(level: i32, proto: i32, predecessor: crate::models::BlockHash, timestamp: crate::models::TimestampProtocol, validation_pass: i32, operations_hash: crate::models::OperationListListHash, fitness: Vec<String>, context: crate::models::ContextHash, priority: i32, proof_of_work_nonce: String, signature: crate::models::Signature) -> Model007PsDelph1BlockHeaderAlphaFullHeader {
        Model007PsDelph1BlockHeaderAlphaFullHeader {
            level,
            proto,
            predecessor,
            timestamp,
            validation_pass,
            operations_hash,
            fitness,
            context,
            priority,
            proof_of_work_nonce,
            seed_nonce_hash: None,
            signature,
        }
    }
}


