/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model007PsDelph1ScriptedContracts {
    #[serde(rename = "code")]
    pub code: crate::models::Micheline007PsDelph1MichelsonV1Expression,
    #[serde(rename = "storage")]
    pub storage: crate::models::Micheline007PsDelph1MichelsonV1Expression,
}

impl Model007PsDelph1ScriptedContracts {
    pub fn new(code: crate::models::Micheline007PsDelph1MichelsonV1Expression, storage: crate::models::Micheline007PsDelph1MichelsonV1Expression) -> Model007PsDelph1ScriptedContracts {
        Model007PsDelph1ScriptedContracts {
            code,
            storage,
        }
    }
}


