/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model007PsDelph1InlinedEndorsement {
    #[serde(rename = "branch")]
    pub branch: crate::models::BlockHash,
    #[serde(rename = "operations")]
    pub operations: crate::models::Model007PsDelph1InlinedEndorsementContents,
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature: Option<crate::models::Signature>,
}

impl Model007PsDelph1InlinedEndorsement {
    pub fn new(branch: crate::models::BlockHash, operations: crate::models::Model007PsDelph1InlinedEndorsementContents) -> Model007PsDelph1InlinedEndorsement {
        Model007PsDelph1InlinedEndorsement {
            branch,
            operations,
            signature: None,
        }
    }
}


