/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model007PsDelph1OperationAlphaInternalOperation {
    #[serde(rename = "source")]
    pub source: crate::models::Model007PsDelph1ContractId,
    #[serde(rename = "nonce")]
    pub nonce: i32,
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "public_key")]
    pub public_key: crate::models::SignaturePublicKey,
    /// Decimal representation of a positive big number
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "destination")]
    pub destination: crate::models::Model007PsDelph1ContractId,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<crate::models::TransactionParameters>,
    /// Decimal representation of a positive big number
    #[serde(rename = "balance")]
    pub balance: String,
    #[serde(rename = "delegate", skip_serializing_if = "Option::is_none")]
    pub delegate: Option<crate::models::SignaturePublicKeyHash>,
    #[serde(rename = "script")]
    pub script: crate::models::Model007PsDelph1ScriptedContracts,
}

impl Model007PsDelph1OperationAlphaInternalOperation {
    pub fn new(source: crate::models::Model007PsDelph1ContractId, nonce: i32, kind: Kind, public_key: crate::models::SignaturePublicKey, amount: String, destination: crate::models::Model007PsDelph1ContractId, balance: String, script: crate::models::Model007PsDelph1ScriptedContracts) -> Model007PsDelph1OperationAlphaInternalOperation {
        Model007PsDelph1OperationAlphaInternalOperation {
            source,
            nonce,
            kind,
            public_key,
            amount,
            destination,
            parameters: None,
            balance,
            delegate: None,
            script,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "delegation")]
    Delegation,
}

