/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Model007PsDelph1ContractId : A contract notation as given to an RPC or inside scripts. Can be a base58 implicit contract hash or a base58 originated contract hash.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model007PsDelph1ContractId {
    #[serde(rename = "invalid_utf8_string")]
    pub invalid_utf8_string: Vec<i32>,
}

impl Model007PsDelph1ContractId {
    /// A contract notation as given to an RPC or inside scripts. Can be a base58 implicit contract hash or a base58 originated contract hash.
    pub fn new(invalid_utf8_string: Vec<i32>) -> Model007PsDelph1ContractId {
        Model007PsDelph1ContractId {
            invalid_utf8_string,
        }
    }
}


