/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model007PsDelph1OperationAlphaUnsignedOperation {
    #[serde(rename = "branch")]
    pub branch: crate::models::BlockHash,
    #[serde(rename = "contents")]
    pub contents: Vec<crate::models::Model007PsDelph1OperationAlphaContents>,
}

impl Model007PsDelph1OperationAlphaUnsignedOperation {
    pub fn new(branch: crate::models::BlockHash, contents: Vec<crate::models::Model007PsDelph1OperationAlphaContents>) -> Model007PsDelph1OperationAlphaUnsignedOperation {
        Model007PsDelph1OperationAlphaUnsignedOperation {
            branch,
            contents,
        }
    }
}


