/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NextOperation {
    #[serde(rename = "protocol")]
    pub protocol: Protocol,
    #[serde(rename = "branch")]
    pub branch: crate::models::BlockHash,
    #[serde(rename = "contents")]
    pub contents: Vec<crate::models::Model007PsDelph1OperationAlphaContents>,
    #[serde(rename = "signature")]
    pub signature: crate::models::Signature,
}

impl NextOperation {
    pub fn new(protocol: Protocol, branch: crate::models::BlockHash, contents: Vec<crate::models::Model007PsDelph1OperationAlphaContents>, signature: crate::models::Signature) -> NextOperation {
        NextOperation {
            protocol,
            branch,
            contents,
            signature,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Protocol {
    #[serde(rename = "PsDELPH1Kxsxt8f9eWbxQeRxkjfbxoqM52jvs5Y5fBxWWh4ifpo")]
    PsDELPH1Kxsxt8f9eWbxQeRxkjfbxoqM52jvs5Y5fBxWWh4ifpo,
}

