/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OperationWithMetadata {
    #[serde(rename = "contents")]
    pub contents: Vec<crate::models::Model007PsDelph1OperationAlphaOperationContentsAndResult>,
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature: Option<crate::models::Signature>,
}

impl OperationWithMetadata {
    pub fn new(contents: Vec<crate::models::Model007PsDelph1OperationAlphaOperationContentsAndResult>) -> OperationWithMetadata {
        OperationWithMetadata {
            contents,
            signature: None,
        }
    }
}


