/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OperationOneOf {
    #[serde(rename = "protocol")]
    pub protocol: Protocol,
    #[serde(rename = "chain_id")]
    pub chain_id: crate::models::ChainId,
    #[serde(rename = "hash")]
    pub hash: crate::models::OperationHash,
    #[serde(rename = "branch")]
    pub branch: crate::models::BlockHash,
}

impl OperationOneOf {
    pub fn new(protocol: Protocol, chain_id: crate::models::ChainId, hash: crate::models::OperationHash, branch: crate::models::BlockHash) -> OperationOneOf {
        OperationOneOf {
            protocol,
            chain_id,
            hash,
            branch,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Protocol {
    #[serde(rename = "ProtoGenesisGenesisGenesisGenesisGenesisGenesk612im")]
    ProtoGenesisGenesisGenesisGenesisGenesisGenesk612im,
}

