/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Origination {
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "source")]
    pub source: crate::models::Model007PsDelph1ContractId,
    #[serde(rename = "nonce")]
    pub nonce: i32,
    /// Decimal representation of a positive big number
    #[serde(rename = "balance")]
    pub balance: String,
    #[serde(rename = "delegate", skip_serializing_if = "Option::is_none")]
    pub delegate: Option<crate::models::SignaturePublicKeyHash>,
    #[serde(rename = "script")]
    pub script: crate::models::Model007PsDelph1ScriptedContracts,
    #[serde(rename = "result")]
    pub result: crate::models::Model007PsDelph1OperationAlphaOperationResultOrigination,
}

impl Origination {
    pub fn new(kind: Kind, source: crate::models::Model007PsDelph1ContractId, nonce: i32, balance: String, script: crate::models::Model007PsDelph1ScriptedContracts, result: crate::models::Model007PsDelph1OperationAlphaOperationResultOrigination) -> Origination {
        Origination {
            kind,
            source,
            nonce,
            balance,
            delegate: None,
            script,
            result,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "origination")]
    Origination,
}

