/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Origination1 {
    #[serde(rename = "source")]
    pub source: crate::models::Model007PsDelph1ContractId,
    #[serde(rename = "nonce")]
    pub nonce: i32,
    #[serde(rename = "kind")]
    pub kind: Kind,
    /// Decimal representation of a positive big number
    #[serde(rename = "balance")]
    pub balance: String,
    #[serde(rename = "delegate", skip_serializing_if = "Option::is_none")]
    pub delegate: Option<crate::models::SignaturePublicKeyHash>,
    #[serde(rename = "script")]
    pub script: crate::models::Model007PsDelph1ScriptedContracts,
}

impl Origination1 {
    pub fn new(source: crate::models::Model007PsDelph1ContractId, nonce: i32, kind: Kind, balance: String, script: crate::models::Model007PsDelph1ScriptedContracts) -> Origination1 {
        Origination1 {
            source,
            nonce,
            kind,
            balance,
            delegate: None,
            script,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "origination")]
    Origination,
}

