/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Reveal2 {
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "source")]
    pub source: crate::models::SignaturePublicKeyHash,
    /// Decimal representation of a positive big number
    #[serde(rename = "fee")]
    pub fee: String,
    /// Decimal representation of a positive big number
    #[serde(rename = "counter")]
    pub counter: String,
    /// Decimal representation of a positive big number
    #[serde(rename = "gas_limit")]
    pub gas_limit: String,
    /// Decimal representation of a positive big number
    #[serde(rename = "storage_limit")]
    pub storage_limit: String,
    #[serde(rename = "public_key")]
    pub public_key: crate::models::SignaturePublicKey,
    #[serde(rename = "metadata")]
    pub metadata: crate::models::Reveal2Metadata,
}

impl Reveal2 {
    pub fn new(kind: Kind, source: crate::models::SignaturePublicKeyHash, fee: String, counter: String, gas_limit: String, storage_limit: String, public_key: crate::models::SignaturePublicKey, metadata: crate::models::Reveal2Metadata) -> Reveal2 {
        Reveal2 {
            kind,
            source,
            fee,
            counter,
            gas_limit,
            storage_limit,
            public_key,
            metadata,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "reveal")]
    Reveal,
}

