/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Reveal1 {
    #[serde(rename = "source")]
    pub source: crate::models::Model007PsDelph1ContractId,
    #[serde(rename = "nonce")]
    pub nonce: i32,
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "public_key")]
    pub public_key: crate::models::SignaturePublicKey,
}

impl Reveal1 {
    pub fn new(source: crate::models::Model007PsDelph1ContractId, nonce: i32, kind: Kind, public_key: crate::models::SignaturePublicKey) -> Reveal1 {
        Reveal1 {
            source,
            nonce,
            kind,
            public_key,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "reveal")]
    Reveal,
}

