/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Running {
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "chain_id")]
    pub chain_id: crate::models::ChainId,
    #[serde(rename = "genesis")]
    pub genesis: crate::models::BlockHash,
    #[serde(rename = "protocol")]
    pub protocol: crate::models::ProtocolHash,
    #[serde(rename = "expiration")]
    pub expiration: crate::models::TimestampProtocol,
}

impl Running {
    pub fn new(status: Status, chain_id: crate::models::ChainId, genesis: crate::models::BlockHash, protocol: crate::models::ProtocolHash, expiration: crate::models::TimestampProtocol) -> Running {
        Running {
            status,
            chain_id,
            genesis,
            protocol,
            expiration,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "running")]
    Running,
}

