/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SeedNonceRevelation {
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "level")]
    pub level: i32,
    #[serde(rename = "nonce")]
    pub nonce: String,
}

impl SeedNonceRevelation {
    pub fn new(kind: Kind, level: i32, nonce: String) -> SeedNonceRevelation {
        SeedNonceRevelation {
            kind,
            level,
            nonce,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "seed_nonce_revelation")]
    SeedNonceRevelation,
}

