/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SeedNonceRevelation1 {
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "level")]
    pub level: i32,
    #[serde(rename = "nonce")]
    pub nonce: String,
    #[serde(rename = "metadata")]
    pub metadata: crate::models::SeedNonceRevelation1Metadata,
}

impl SeedNonceRevelation1 {
    pub fn new(kind: Kind, level: i32, nonce: String, metadata: crate::models::SeedNonceRevelation1Metadata) -> SeedNonceRevelation1 {
        SeedNonceRevelation1 {
            kind,
            level,
            nonce,
            metadata,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "seed_nonce_revelation")]
    SeedNonceRevelation,
}

