/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SeedNonceRevelation1Metadata {
    #[serde(rename = "balance_updates")]
    pub balance_updates: Vec<crate::models::OneOfobjectobjectobjectobject>,
}

impl SeedNonceRevelation1Metadata {
    pub fn new(balance_updates: Vec<crate::models::OneOfobjectobjectobjectobject>) -> SeedNonceRevelation1Metadata {
        SeedNonceRevelation1Metadata {
            balance_updates,
        }
    }
}


