/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct String {
    #[serde(rename = "string")]
    pub string: crate::models::Unistring,
}

impl String {
    pub fn new(string: crate::models::Unistring) -> String {
        String {
            string,
        }
    }
}


