/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TestChainStatus : The status of the test chain: not_running (there is no test chain at the moment), forking (the test chain is being setup), running (the test chain is running).



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TestChainStatus {
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "protocol")]
    pub protocol: crate::models::ProtocolHash,
    #[serde(rename = "expiration")]
    pub expiration: crate::models::TimestampProtocol,
    #[serde(rename = "chain_id")]
    pub chain_id: crate::models::ChainId,
    #[serde(rename = "genesis")]
    pub genesis: crate::models::BlockHash,
}

impl TestChainStatus {
    /// The status of the test chain: not_running (there is no test chain at the moment), forking (the test chain is being setup), running (the test chain is running).
    pub fn new(status: Status, protocol: crate::models::ProtocolHash, expiration: crate::models::TimestampProtocol, chain_id: crate::models::ChainId, genesis: crate::models::BlockHash) -> TestChainStatus {
        TestChainStatus {
            status,
            protocol,
            expiration,
            chain_id,
            genesis,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "running")]
    Running,
}

