/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TimestampProtocol : A timestamp as seen by the protocol: second-level precision, epoch based.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimestampProtocol {
    #[serde(rename = "invalid_utf8_string")]
    pub invalid_utf8_string: Vec<i32>,
}

impl TimestampProtocol {
    /// A timestamp as seen by the protocol: second-level precision, epoch based.
    pub fn new(invalid_utf8_string: Vec<i32>) -> TimestampProtocol {
        TimestampProtocol {
            invalid_utf8_string,
        }
    }
}


