/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Transaction {
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "source")]
    pub source: crate::models::Model007PsDelph1ContractId,
    #[serde(rename = "nonce")]
    pub nonce: i32,
    /// Decimal representation of a positive big number
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "destination")]
    pub destination: crate::models::Model007PsDelph1ContractId,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<crate::models::TransactionParameters>,
    #[serde(rename = "result")]
    pub result: crate::models::Model007PsDelph1OperationAlphaOperationResultTransaction,
}

impl Transaction {
    pub fn new(kind: Kind, source: crate::models::Model007PsDelph1ContractId, nonce: i32, amount: String, destination: crate::models::Model007PsDelph1ContractId, result: crate::models::Model007PsDelph1OperationAlphaOperationResultTransaction) -> Transaction {
        Transaction {
            kind,
            source,
            nonce,
            amount,
            destination,
            parameters: None,
            result,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "transaction")]
    Transaction,
}

