/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionParameters {
    #[serde(rename = "entrypoint")]
    pub entrypoint: crate::models::Model007PsDelph1Entrypoint,
    #[serde(rename = "value")]
    pub value: crate::models::Micheline007PsDelph1MichelsonV1Expression,
}

impl TransactionParameters {
    pub fn new(entrypoint: crate::models::Model007PsDelph1Entrypoint, value: crate::models::Micheline007PsDelph1MichelsonV1Expression) -> TransactionParameters {
        TransactionParameters {
            entrypoint,
            value,
        }
    }
}


