/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Transaction1 {
    #[serde(rename = "source")]
    pub source: crate::models::Model007PsDelph1ContractId,
    #[serde(rename = "nonce")]
    pub nonce: i32,
    #[serde(rename = "kind")]
    pub kind: Kind,
    /// Decimal representation of a positive big number
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "destination")]
    pub destination: crate::models::Model007PsDelph1ContractId,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<crate::models::TransactionParameters>,
}

impl Transaction1 {
    pub fn new(source: crate::models::Model007PsDelph1ContractId, nonce: i32, kind: Kind, amount: String, destination: crate::models::Model007PsDelph1ContractId) -> Transaction1 {
        Transaction1 {
            source,
            nonce,
            kind,
            amount,
            destination,
            parameters: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "transaction")]
    Transaction,
}

