/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Bytes {
    #[serde(rename = "bytes")]
    pub bytes: String,
}

impl Bytes {
    pub fn new(bytes: String) -> Bytes {
        Bytes {
            bytes,
        }
    }
}


