/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Int {
    /// Decimal representation of a big number
    #[serde(rename = "int")]
    pub int: String,
}

impl Int {
    pub fn new(int: String) -> Int {
        Int {
            int,
        }
    }
}


