/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Micheline007PsDelph1MichelsonV1Expression {
    /// Decimal representation of a big number
    #[serde(rename = "int")]
    pub int: String,
    #[serde(rename = "string")]
    pub string: crate::models::Unistring,
    #[serde(rename = "bytes")]
    pub bytes: String,
    #[serde(rename = "prim")]
    pub prim: crate::models::Model007PsDelph1MichelsonV1Primitives,
    #[serde(rename = "args", skip_serializing_if = "Option::is_none")]
    pub args: Option<Vec<crate::models::Micheline007PsDelph1MichelsonV1Expression>>,
    #[serde(rename = "annots", skip_serializing_if = "Option::is_none")]
    pub annots: Option<Vec<String>>,
}

impl Micheline007PsDelph1MichelsonV1Expression {
    pub fn new(int: String, string: crate::models::Unistring, bytes: String, prim: crate::models::Model007PsDelph1MichelsonV1Primitives) -> Micheline007PsDelph1MichelsonV1Expression {
        Micheline007PsDelph1MichelsonV1Expression {
            int,
            string,
            bytes,
            prim,
            args: None,
            annots: None,
        }
    }
}


