/*
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 7.5
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Model007PsDelph1MichelsonV1Primitives {
    #[serde(rename = "ADD")]
    ADD,
    #[serde(rename = "IF_NONE")]
    IFNONE,
    #[serde(rename = "SWAP")]
    SWAP,
    #[serde(rename = "set")]
    Set,
    #[serde(rename = "nat")]
    Nat,
    #[serde(rename = "CHECK_SIGNATURE")]
    CHECKSIGNATURE,
    #[serde(rename = "IF_LEFT")]
    IFLEFT,
    #[serde(rename = "LAMBDA")]
    LAMBDA,
    #[serde(rename = "Elt")]
    Elt,
    #[serde(rename = "CREATE_CONTRACT")]
    CREATECONTRACT,
    #[serde(rename = "NEG")]
    NEG,
    #[serde(rename = "big_map")]
    BigMap,
    #[serde(rename = "map")]
    Map,
    #[serde(rename = "or")]
    Or,
    #[serde(rename = "BLAKE2B")]
    BLAKE2B,
    #[serde(rename = "bytes")]
    Bytes,
    #[serde(rename = "SHA256")]
    SHA256,
    #[serde(rename = "SET_DELEGATE")]
    SETDELEGATE,
    #[serde(rename = "CONTRACT")]
    CONTRACT,
    #[serde(rename = "LSL")]
    LSL,
    #[serde(rename = "SUB")]
    SUB,
    #[serde(rename = "IMPLICIT_ACCOUNT")]
    IMPLICITACCOUNT,
    #[serde(rename = "PACK")]
    PACK,
    #[serde(rename = "list")]
    List,
    #[serde(rename = "PAIR")]
    PAIR,
    #[serde(rename = "Right")]
    Right,
    #[serde(rename = "contract")]
    Contract,
    #[serde(rename = "GT")]
    GT,
    #[serde(rename = "LEFT")]
    LEFT,
    #[serde(rename = "STEPS_TO_QUOTA")]
    STEPSTOQUOTA,
    #[serde(rename = "storage")]
    Storage,
    #[serde(rename = "TRANSFER_TOKENS")]
    TRANSFERTOKENS,
    #[serde(rename = "CDR")]
    CDR,
    #[serde(rename = "SLICE")]
    SLICE,
    #[serde(rename = "PUSH")]
    PUSH,
    #[serde(rename = "False")]
    _False,
    #[serde(rename = "SHA512")]
    SHA512,
    #[serde(rename = "CHAIN_ID")]
    CHAINID,
    #[serde(rename = "BALANCE")]
    BALANCE,
    #[serde(rename = "signature")]
    Signature,
    #[serde(rename = "DUG")]
    DUG,
    #[serde(rename = "SELF")]
    _SELF,
    #[serde(rename = "EMPTY_BIG_MAP")]
    EMPTYBIGMAP,
    #[serde(rename = "LSR")]
    LSR,
    #[serde(rename = "OR")]
    OR,
    #[serde(rename = "XOR")]
    XOR,
    #[serde(rename = "lambda")]
    Lambda,
    #[serde(rename = "COMPARE")]
    COMPARE,
    #[serde(rename = "key")]
    Key,
    #[serde(rename = "option")]
    Option,
    #[serde(rename = "Unit")]
    Unit,
    #[serde(rename = "Some")]
    Some,
    #[serde(rename = "UNPACK")]
    UNPACK,
    #[serde(rename = "NEQ")]
    NEQ,
    #[serde(rename = "INT")]
    INT,
    #[serde(rename = "pair")]
    Pair,
    #[serde(rename = "AMOUNT")]
    AMOUNT,
    #[serde(rename = "DIP")]
    DIP,
    #[serde(rename = "ABS")]
    ABS,
    #[serde(rename = "ISNAT")]
    ISNAT,
    #[serde(rename = "EXEC")]
    EXEC,
    #[serde(rename = "NOW")]
    NOW,
    #[serde(rename = "LOOP")]
    _LOOP,
    #[serde(rename = "chain_id")]
    ChainId,
    #[serde(rename = "string")]
    String,
    #[serde(rename = "MEM")]
    MEM,
    #[serde(rename = "MAP")]
    MAP,
    #[serde(rename = "None")]
    None,
    #[serde(rename = "address")]
    Address,
    #[serde(rename = "CONCAT")]
    CONCAT,
    #[serde(rename = "EMPTY_SET")]
    EMPTYSET,
    #[serde(rename = "MUL")]
    MUL,
    #[serde(rename = "LOOP_LEFT")]
    LOOPLEFT,
    #[serde(rename = "timestamp")]
    Timestamp,
    #[serde(rename = "LT")]
    LT,
    #[serde(rename = "UPDATE")]
    UPDATE,
    #[serde(rename = "DUP")]
    DUP,
    #[serde(rename = "SOURCE")]
    SOURCE,
    #[serde(rename = "mutez")]
    Mutez,
    #[serde(rename = "SENDER")]
    SENDER,
    #[serde(rename = "IF_CONS")]
    IFCONS,
    #[serde(rename = "RIGHT")]
    RIGHT,
    #[serde(rename = "CAR")]
    CAR,
    #[serde(rename = "CONS")]
    CONS,
    #[serde(rename = "LE")]
    LE,
    #[serde(rename = "NONE")]
    NONE,
    #[serde(rename = "IF")]
    _IF,
    #[serde(rename = "SOME")]
    SOME,
    #[serde(rename = "GET")]
    GET,
    #[serde(rename = "Left")]
    Left,
    #[serde(rename = "CAST")]
    CAST,
    #[serde(rename = "int")]
    Int,
    #[serde(rename = "SIZE")]
    SIZE,
    #[serde(rename = "key_hash")]
    KeyHash,
    #[serde(rename = "unit")]
    Unit,
    #[serde(rename = "DROP")]
    DROP,
    #[serde(rename = "EMPTY_MAP")]
    EMPTYMAP,
    #[serde(rename = "NIL")]
    NIL,
    #[serde(rename = "DIG")]
    DIG,
    #[serde(rename = "APPLY")]
    APPLY,
    #[serde(rename = "bool")]
    Bool,
    #[serde(rename = "RENAME")]
    RENAME,
    #[serde(rename = "operation")]
    Operation,
    #[serde(rename = "True")]
    _True,
    #[serde(rename = "FAILWITH")]
    FAILWITH,
    #[serde(rename = "parameter")]
    Parameter,
    #[serde(rename = "HASH_KEY")]
    HASHKEY,
    #[serde(rename = "EQ")]
    EQ,
    #[serde(rename = "NOT")]
    NOT,
    #[serde(rename = "UNIT")]
    UNIT,
    #[serde(rename = "Pair")]
    Pair,
    #[serde(rename = "ADDRESS")]
    ADDRESS,
    #[serde(rename = "EDIV")]
    EDIV,
    #[serde(rename = "CREATE_ACCOUNT")]
    CREATEACCOUNT,
    #[serde(rename = "GE")]
    GE,
    #[serde(rename = "ITER")]
    ITER,
    #[serde(rename = "code")]
    Code,
    #[serde(rename = "AND")]
    AND,

}




